# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "env/dev" branch
  pull_request:
    types: [closed]
    branches: [ "env-dev", "env-tst", "env-prd" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Environment variables
    environment:
      name: ${{ github.base_ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: log info
        run: | 
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 Repository is ${{ github.repository }} and branch is {{ github.event.pull_request.head.ref }}"
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: check which GH environment was picked    
        run: echo $URL
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: list directory contents recursively
        run: ls -lR

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
